-- OpenSlot v1.2 fresh-project schema. Review before running against an existing schema.
create extension if not exists pgcrypto;
create type public.business_type as enum ('service','restaurant','catering');
create type public.slot_type as enum ('service','dining','catering');
create type public.slot_status as enum ('draft','open','booked','expired','cancelled');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,created_at timestamptz default now());
create table public.businesses(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,name text not null,business_type public.business_type not null,city text,subscription_plan text default 'pilot',created_at timestamptz default now());
create table public.calendar_connections(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,provider text not null check(provider in ('google','square')),external_account_id text,status text not null default 'pending',created_at timestamptz default now(),unique(business_id,provider));
create table public.open_slots(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,slot_type public.slot_type not null,title text not null,description text,start_at timestamptz,end_at timestamptz,expires_at timestamptz not null,price_cents integer check(price_cents is null or price_cents>=0),regular_price_cents integer,party_size integer check(party_size is null or party_size>0),quantity_available integer not null default 1 check(quantity_available>=0),serves_min integer,serves_max integer,fulfilment text check(fulfilment is null or fulfilment in ('onsite','pickup','delivery','pickup_delivery')),source text not null default 'manual' check(source in ('manual','google','square')),status public.slot_status not null default 'open',created_at timestamptz default now());
create table public.bookings(id uuid primary key default gen_random_uuid(),slot_id uuid not null references public.open_slots(id),customer_id uuid not null references auth.users(id),quantity integer not null default 1 check(quantity>0),status text not null default 'confirmed',created_at timestamptz default now());
create table public.favourites(user_id uuid references auth.users(id) on delete cascade,slot_id uuid references public.open_slots(id) on delete cascade,created_at timestamptz default now(),primary key(user_id,slot_id));
alter table public.profiles enable row level security;alter table public.businesses enable row level security;alter table public.calendar_connections enable row level security;alter table public.open_slots enable row level security;alter table public.bookings enable row level security;alter table public.favourites enable row level security;
create policy "public business read" on public.businesses for select using(true);create policy "owner manages business" on public.businesses for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "public open slot read" on public.open_slots for select using(status='open' and expires_at>now());create policy "owner manages slots" on public.open_slots for all to authenticated using(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid())) with check(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid()));
create policy "owner manages calendar" on public.calendar_connections for all to authenticated using(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid())) with check(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid()));create policy "user profile" on public.profiles for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy "customer bookings read" on public.bookings for select to authenticated using(customer_id=auth.uid() or exists(select 1 from public.open_slots s join public.businesses b on b.id=s.business_id where s.id=slot_id and b.owner_id=auth.uid()));create policy "customer favourites" on public.favourites for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create or replace function public.book_open_slot(p_slot_id uuid,p_quantity integer default 1) returns uuid language plpgsql security definer set search_path=public as $$ declare s public.open_slots%rowtype; bid uuid; begin if auth.uid() is null then raise exception 'Authentication required';end if;select * into s from public.open_slots where id=p_slot_id for update;if not found or s.status<>'open' or s.expires_at<=now() then raise exception 'Slot unavailable';end if;if p_quantity<1 or s.quantity_available<p_quantity then raise exception 'Insufficient availability';end if;insert into public.bookings(slot_id,customer_id,quantity) values(p_slot_id,auth.uid(),p_quantity) returning id into bid;update public.open_slots set quantity_available=quantity_available-p_quantity,status=case when quantity_available-p_quantity=0 then 'booked'::public.slot_status else status end where id=p_slot_id;return bid;end $$;
revoke all on function public.book_open_slot(uuid,integer) from public;grant execute on function public.book_open_slot(uuid,integer) to authenticated;
